services:
  as:
    build: ./AS
    container_name: as
    ports:
      - "53533:53533/udp"
    volumes:
      - ./AS:/app   # so you can see records.txt locally

  fs:
    build: ./FS
    container_name: fs
    ports:
      - "9090:9090"
    depends_on:
      - as

  us:
    build: ./US
    container_name: us
    ports:
      - "8080:8080"
    depends_on:
      - as
      - fs
